### ISSUE TITLE
Form for new OSGeo Website

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/admin#1]
Fill form indicated on this mail:
https://lists.osgeo.org/pipermail/discuss/2017-July/017629.html

## tasks

- [ ] pgRouting logo `.svg` format URL
- [ ] Screenshot URL
- [ ] Team Photo URL

**Comment by cvvergara** [comment]
http://pgrouting.org/resources/pgrouting-logo.svg
http://pgrouting.org/resources/pgrouting-team.jpg
http://pgrouting.org/resources/pgrouting-screenshot.png

**Comment by dkastl** [comment]
What about "hosting" the images on this Github repository on a "media" folder?

**Comment by cvvergara** [comment]
Task
- [ ] put originals in this repo

**Comment by dkastl** [comment]
We could actually also save the content of the form here, so we can easily submit an update.

**Comment by cvvergara** [comment]
From answers
--

Here's what we got from you:

- **Email address**
  - project@pgrouting.org
- **Project Name**   Please  use the full name of your project (so "JTS Toplogy Suite" not "JTS")  and avoid making it complicated (so "Orfeo ToolBox" not "Orfeo ToolBox  (OTB)".
  -  pgRouting
- **Logo URL**  Please  provide a high quality SVG logo (we will display with an appropriate  amount of whitespace). If your project has a branding guide you may  provide the link here).
  -  http://pgrouting.org/resources/pgrouting-logo.svg
- **Website URL**  * Link to project home page
  -  http://pgrouting.org
- **Project Blurb**  * Short  paragraph describing what this project is for to "GIS Professionals"  (or "IT Professionals" if you are a software library).
  - pgRouting extends the PostGIS / PostgreSQL geospatial database providing routing functionality       
- **Screenshot URL**  links to screenshot of your project, show us what it looks like! We can make it in a browser or laptop "frame".  
  - http://pgrouting.org/resources/pgrouting-screenshot.png
- **Team Photo URL**  Link to a photo of your team; we want the website to show people!  
  - http://pgrouting.org/resources/pgrouting-team.jpg       
- **Project Affiliation**  * Please tell us if this project is part of OSGeo or another software foundation
  - OSGeo Community Project (includes incubation projects)
- **Core - Features**  * What  are the core features of your project ? Can it be routing calculation,  reprojection, data management, web services?  For examples see the OSGeo  Live project overviews on https://live.osgeo.org/en/overview/geonode_overview.html ).
```
  pgRouting provides functions for:
  *   All pairs Johnson’s and Floyd-Warshall Algorithms
  *   Dijkstra and Bi-directional Dijkstra Algorithms
  *   A* and Bi-directional A* Algorithms 
  *   Driving distance 
  *   And many more
```
-  **Implemented Standards**  What  standards are implemented (WMS,WFS,..KML)  ISO standards (ISO 19115)  ITF (GeoJson). Is it OGC compliant or a reference implementation?  Community standard (GeoTiff, MapBox Style).
    - No answer
- **Project type**  * What  is your project type ? Please choose the ones who fits the best wit  your project in the list.  these are the same project types we use now  on osgeo.org.
  - Geospatial libraries
- **Level 1 - Topic**  These tags are used to guide new users to your project (as an example QGIS would be listed as both Cartography and Analysis).
  -  Analysis and Processing 
- **Level 2 - Information Technology**
  - Database
- **Level 2 - Development**
  - Library
- **Who is involved ? **
 - @cvvergara @dkastl @iamrohith94 @robe2 @woodbri 
- **Tools/Libraries Based on** 
  - postGIS, Boost Graph Library, CGAL
- **Twitter URL**
  - @pgrouting
- **Facebook URL** 
  - No answer
- **Blog URL**
  - No answer
- **General Email or mailing list**
  - pgrouting-users at lists.osgeo.org
- **Info Sheet URL**
  - No answer
- **User Quickstart URL**
  - http://workshop.pgrouting.org/
- **Documentation URL**
  - http://docs.pgrouting.org/
- **Demo URL**
  - No answer
- **Support URL**
  - http://pgrouting.org/support.html
- **Download URL**
  - http://pgrouting.org/download.html
- **Issue Tracker URL**
  - https://github.com/pgRouting/pgrouting/issues
- **Source Code URL**
  - https://github.com/pgRouting/pgrouting
- **Developer Quickstart URL**
  - http://docs.pgrouting.org/#pgrouting-developers
- **List of Contributors URL**
  - https://github.com/pgRouting/pgrouting/graphs/contributors
- **Roadmap URL**
  - no answer
- **Metrics URL**
  - https://www.openhub.net/p/pgrouting
- **Pulse URL**
  - https://github.com/pgRouting/pgrouting/pulse/monthly
- **Similar Projects**
  - osrm-backend
- **Similar Proprietary Software**
  - No answer
- **License**
  -    GPL
- **Current Version**
  - 2.4.1
- **Supported Platforms**
  -  Linux / Unix
  -  Mac OSX
  -  Windows
- **API Interfaces**
  - No answer
- **Languages**
  - SQL, C, C++

**Comment by cvvergara** [comment]
@dkastl 
I think it looks better, but I am not happy with the image of the elephants.
It cropped it, and it looks out of focus.
http://osgeo.getinteractive.nl/projects/pgRouting/
I am very open to suggestions
