### ISSUE TITLE
Create flyer

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/admin#5]
Mails refering to this task:
https://lists.osgeo.org/pipermail/marketing/2017-July/003790.html
https://lists.osgeo.org/pipermail/marketing/2017-July/003791.html

## tasks
- [x] fork osgeo repository on pgRouting organization
- [x] create pgRouting branch to work on.
- [x] make the flyer
- [x] fix flyer
- [x] make a wiki of instructions on how to make the flyer (in our fork)
- [x] make PR to osgeo repository
- [x] wait for merge before closing this issue

**Comment by cvvergara** [comment]
Merge was done

**Comment by dkastl** [comment]
Btw., I started to like Postcards. They are easier to make because they need less content.
And they have some impact ... and they are small and can be sent somewhere.
I will try to make some proposal.
